name: isra
description: A single player puzzle game
publish_to: "none"
version: 1.0.1+3

environment:
    sdk: ">=3.0.5 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_riverpod: ^1.0.4
    uuid: ^3.0.6
    flutter_swipe_detector: ^2.0.0
    hive: ^2.1.1
    hive_flutter: ^1.1.0
    json_annotation: ^4.5.0
    flutter_svg: ^2.0.7
    introduction_screen: ^3.1.12
    google_fonts: ^6.2.0
    shared_preferences: ^2.2.2
    flutter_native_splash: ^2.3.7
    flame_audio: ^2.1.1
    games_services: ^4.0.1
    google_mobile_ads: ^5.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
    build_runner: ^2.1.11
    json_serializable: ^6.2.0

flutter:
    fonts:
        - family: NotoSansEthiopic
          fonts:
              - asset: fonts/NotoSansEthiopic-VariableFont_wdth,wght.ttf
    uses-material-design: true
    assets:
        - assets/icon.png
        - assets/splash.png
        - assets/icon.svg
        - assets/step1.svg
        - assets/step2.svg
        - assets/step3.svg
        - assets/audio/addis-ababa.mp3

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icon.png"
    remove_alpha_ios: true
